In [ ]:

#this is the notebook for week1 of the class 'Numerical Methods for AI' CSE190
#introduction to calculus and linear algebra and python language


In [31]:
#the first easiest program in Python and its output below
print ("Hello, World!")

Hello, World!


In [105]:
#a more complicated program
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

arr = [3,6,8,9,2,4,1]
print("sorting array %s" % (str)(arr))
print(quicksort(arr))

sorting array [3, 6, 8, 9, 2, 4, 1]
[1, 2, 3, 4, 6, 8, 9]


In [33]:
#Variables
x = 5
y = 2
string = "Hello, World!"
z = x + y
print(x,y,z,string)

5 2 7 Hello, World!


In [36]:
listt = [] #empty list
zeros_list = [0] * 10 #generating list of zeros
print(listt, zeros_list)
listt.append(1)# append to empty list
print(listt, len(listt))

[] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1]


In [12]:
#generate a list of sequential integers 
nums = list(range(10))
print(nums)
#slicing examples
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1]) #-1 means here upto the one before the last element
print(nums[::-1]) #printing in reverse
print(nums[0:-1:2]) #printing elements on even positions
nums[0:4] = [4,3,2,1,0]
print(nums)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3]
[2, 3, 4, 5, 6, 7, 8, 9]
[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[0, 2, 4, 6, 8]
[4, 3, 2, 1, 0, 4, 5, 6, 7, 8, 9]


In [15]:
#a standard way of defining a function
def add_numbers(a, b):
    return a + b
print(add_numbers(3, 4))

#lambda function
lambda_add_numbers = lambda a, b: a + b
print(lambda_add_numbers(3, 4))

7
7


In [120]:
#example of a class
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()

Hello, Fred


In [2]:
filled_list = [a/2 for a in range(10)]
print(filled_list)

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]


In [3]:
#looping over a list, and printing the output
for i in range(10):
    print ("Looping %f" % filled_list[i])

Looping 0.000000
Looping 0.500000
Looping 1.000000
Looping 1.500000
Looping 2.000000
Looping 2.500000
Looping 3.000000
Looping 3.500000
Looping 4.000000
Looping 4.500000


In [115]:
#another way of looping over the list
for elem in filled_list:
    print(elem)

0.0
0.5
1.0
1.5
2.0
2.5
3.0
3.5
4.0
4.5


In [119]:
#list comprehension - 
#concise notation for generating a new list
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums if x % 2 == 0] # if x is even
print(squares) 

[0, 4, 16]


In [85]:
#importing numpy -- very powerful toolbox
import numpy as np

In [229]:
#some different ways of creating vectors in numpy
vector = np.zeros((5,), dtype = float)
print(vector)

#given (column) vector
vec = np.array([ [1],[2], [3], [4], [5]])
print(vec)

#a different way of defining a column vector
vec2 =  np.array([1, 2, 3, 4, 5]).reshape((5,1))
print(vec2)

[0. 0. 0. 0. 0.]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [87]:
#basic vector operations
#addition
r1 = vec + vec2
print(r1)
print( "vec + vec2 = %s" % (str)(r1))
#componentwise product
r2 = vec * vec2
print(r2)
print( "vec * vec2 = %s" % (str)(r2))
#scalar multiplication
r3 = 3 * vec
print( " 3 * vec = %s" % (str)(r3))
#dot product
r4 = np.dot( np.squeeze(r1), np.squeeze(r2) )
print( "dot product = %d" % r4)

#(Euclidean)norm of a vector
norm = np.linalg.norm(vec)
print("Euclidean norm of the vector %s = %d" % ((str)(vec), norm))
mnorm = np.linalg.norm(vec, 1)
print("'Manhattan' norm of the vector %s = %d" % ((str)(vec), mnorm))

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]
vec + vec2 = [[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]
[[ 1]
 [ 4]
 [ 9]
 [16]
 [25]]
vec * vec2 = [[ 1]
 [ 4]
 [ 9]
 [16]
 [25]]
 3 * vec = [[ 3]
 [ 6]
 [ 9]
 [12]
 [15]]
dot product = 450
Euclidean norm of the vector [[1]
 [2]
 [3]
 [4]
 [5]] = 7
'Manhattan' norm of the vector [[1]
 [2]
 [3]
 [4]
 [5]] = 15


In [7]:
import numpy as np
#matrices
M = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

N = np.array([[1, 0, 0], 
              [0, 1, 0], 
              [0, 0, 1]])

#addition of matrices
R1 = M + N
print(R1)
#ELEMENTWISE multiplication of matrices
R2 = M*N
print(R2)
#product of two matrices
R3 = np.dot(M, N)
print(R3)
#matrix dimension
print(M.shape)

[[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]]
[[1 0 0]
 [0 5 0]
 [0 0 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [14]:
#matrix times vector product
print(M)
vec = np.array([ [1],[2], [3]])
print(vec)
R = np.dot(M, vec)
print(R)
print(R.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]]
[[14]
 [32]
 [50]]
(3, 1)


In [90]:
#other ways of creating matrices
#zeros matrix
zM = np.zeros((3,3))
print(zM)
#ones matrix
oM = np.ones( (3,3))
print(oM)
#given element matrix
sM = np.full((3,3), 6)
print(sM)
# a random matrix
rM = np.random.random( (3,3) )
print(rM)
#identity matrix
Id = np.eye( 3 )
print(Id)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[0.27053395 0.78606557 0.97035595]
 [0.52679812 0.27318018 0.53061996]
 [0.26108459 0.29791167 0.00438492]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [113]:
#matrix indexing and slicing
M = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(M)
print(M[0:2,0:2])
print(M[:,0:2])
print(M[1:,1:])
print(M[1:-1,1:-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[1 2]
 [4 5]
 [7 8]]
[[5 6]
 [8 9]]
[[5]]


In [124]:
#more advanced matrix indexing using indexing arrays
#set the diagonal to zero
indices = [ [0,1,2], [0,1,2] ] 
print(M[indices])
M[indices] = 0
print(M)


[0 0 0]
[[0 2 3]
 [4 0 6]
 [7 8 0]]


In [15]:
#Boolean array indexing: 
#Boolean array indexing lets you pick out arbitrary elements of an array
M = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
boolidx = M > 4
print(boolidx)
M[boolidx] = -1
print(M)

[[False False False]
 [False  True  True]
 [ True  True  True]]
[[ 1  2  3]
 [ 4 -1 -1]
 [-1 -1 -1]]


In [92]:
#matrix operations
#*transpose M.T
print(M)
print(M.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [231]:
#a symmetric matrix
S = np.array([[1, 2, 3],
             [2, 1, 2],
             [3, 2, 1]])
print(S)
print(S.T)
print( np.array_equal(S, S.T) )

[[1 2 3]
 [2 1 2]
 [3 2 1]]
[[1 2 3]
 [2 1 2]
 [3 2 1]]
True


In [232]:
#broadcasting for matrices
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([5, 0, 5])
y = x + v
print(y) 

[[ 6  2  8]
 [ 9  5 11]
 [12  8 14]
 [15 11 17]]


In [233]:
#matrix determinant
detS = np.linalg.det(S)
print(detS)

8.000000000000002


In [235]:
#if determinant is nonzero we can invert the matrix
invS = np.linalg.inv(S)
print(invS)

badS = np.array([[1, 2, 3],
                 [2, 1, 2],
                 [3, 3, 5]])
#oooops badS is NONinvertible
invBadS = np.linalg.inv(badS)
print("inverse of badS =\n%s" % (str)(invBadS))
print("very large numbers, because this matrix is noninvertible. how to check it ?")
detBadS = np.linalg.det(badS)
print("determinant of badS = %f" % detBadS)

[[-0.375  0.5    0.125]
 [ 0.5   -1.     0.5  ]
 [ 0.125  0.5   -0.375]]
inverse of badS =
[[-7.50599938e+14 -7.50599938e+14  7.50599938e+14]
 [-3.00239975e+15 -3.00239975e+15  3.00239975e+15]
 [ 2.25179981e+15  2.25179981e+15 -2.25179981e+15]]
very large numbers, because this matrix is noninvertible. how to check it ?
determinant of badS = 0.000000


In [99]:
#computation of eigenvalues
M = np.array([[0, 1],[-2, -3]])
eigvals, eigvecs = np.linalg.eig(M)
print("eigenvalues =%s" % (str)(eigvals))
print("eigenvectors =%s" % (str)(eigvecs))

eigenvalues =[-1. -2.]
eigenvectors =[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


In [97]:
#computation of eigenvalues of a noninvertible matrix
eigvals, eigvecs = np.linalg.eig(badS)
print("eigenvalues =%s" % (str)(eigvals))
print("eigenvectors =%s" % (str)(eigvecs))

eigenvalues =[ 8.00000000e+00 -1.00000000e+00  4.65122058e-16]
eigenvectors =[[ 4.52678730e-01  7.07106781e-01 -1.96116135e-01]
 [ 3.62142984e-01 -7.07106781e-01 -7.84464541e-01]
 [ 8.14821714e-01 -2.07739808e-17  5.88348405e-01]]


In [102]:
#SVD - Singular Value Decomposition
U, S, VT = np.linalg.svd(M)
print("U =%s" % (str)(U))
print("S =%s" % (str)(S))
print("VT =%s" % (str)(VT))
#compute the product U*S*VT to see if its the same matrix
P = np.dot( np.dot(U, np.diag(S)), VT)
print("P =%s" % (str)(P))

U =[[-0.22975292  0.97324899]
 [ 0.97324899  0.22975292]]
S =[3.70245917 0.54018151]
VT =[[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]]
P =[[-1.21244049e-16  1.00000000e+00]
 [-2.00000000e+00 -3.00000000e+00]]


In [ ]:
#!HOMEWORK
#compute the rotation angles represented by the transform matrices U and V 

In [236]:
#projection onto two PCA components of a high dimensional data matrix
A = np.array([
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]])
print("matrix A:")
print(A)
# Singular-value decomposition
U, s, VT = np.linalg.svd(A)
# populate Sigma with n x n diagonal matrix
Sigma = np.diag(s)
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]
#check if  the original matrix  is reconstructed
B = U.dot(Sigma.dot(VT))
print(B)
# project all datapoints in A onto the principal eigenvectors
print("rows of matrix A projected onto two principal eigenvectors:")
T = A.dot(VT.T)
print(T)

matrix A:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
rows of matrix A projected onto two principal eigenvectors:
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [237]:
#various methods of solving systems of linear equations

#we want to solve the system
# Ax = b , i.e. find vector x , which satisfy this equation
# the fist method is to invert A, i.e. x = A^(-1)b
A = np.array( [ [2,1,1], [6,2,1], [-2, 2, 1] ] )
b = np. array( [[1],[-1],[7]])
x = np.zeros(3)

Ainv  = np.linalg.inv(A)
x = np.dot(Ainv, b)
print(x)
#test the computed solution (if Ax == b)
result = np.dot(A, x)
print(result)

#!HOMEWORK
#solve linear system using the Cramers' rule
#look for the algorithm in the shared Meyer's book


[[-1.]
 [ 2.]
 [ 1.]]
[[ 1.]
 [-1.]
 [ 7.]]


In [243]:
 #use scipy library
import scipy.linalg

#what about systems determined by nonsquare matrices?
#example of putting a matrix in the row-echelon form
A = np.array([ [1,2,1,3,3], [2,4,0,4,4], [1,2,3,5,5], [2,4,0,4,7] ])
b = np.array([ [5], [6], [9], [9] ])

x = np.zeros(4)

P, L, U = scipy.linalg.lu(A)

print("matrix A:")
print(A)
print("vector b:")
print(b)
print("LU decomposition of matrix A (first L, second U):")
print( L )
print( U )

#recompute the matrix
R = P.dot(L.dot(U))
print("L*U (for testing):")
print(R)


#print the infnite set of solutions
Pinv = np.linalg.inv(P)
Linv = np.linalg.inv(L)
print( (Linv.dot(Pinv)).dot(b) )

print("the infinite set of solutions to Ax = b ")
s = ""
for i in range(4): #iterate over rows
    for j in range(5): #iterate over columns
        if(U[i,j] != 0):
            s += "%dx_%d" % (U[i,j], j+1)
            if(j < 4):
                s+= "+"
    s += " = %d\n" % b[i]
print(s)
    

matrix A:
[[1 2 1 3 3]
 [2 4 0 4 4]
 [1 2 3 5 5]
 [2 4 0 4 7]]
vector b:
[[5]
 [6]
 [9]
 [9]]
LU decomposition of matrix A (first L, second U):
[[1.  0.  0.  0. ]
 [0.5 1.  0.  0. ]
 [0.5 0.  1.  0. ]
 [1.  0.  0.  1. ]]
[[2. 4. 0. 4. 4.]
 [0. 0. 1. 1. 1.]
 [0. 0. 3. 3. 3.]
 [0. 0. 0. 0. 3.]]
L*U (for testing):
[[1. 2. 1. 3. 3.]
 [2. 4. 0. 4. 4.]
 [1. 2. 3. 5. 5.]
 [2. 4. 0. 4. 7.]]
[[6.]
 [2.]
 [6.]
 [3.]]
the infinite set of solutions to Ax = b 
2x_1+4x_2+4x_4+4x_5 = 5
1x_3+1x_4+1x_5 = 6
3x_3+3x_4+3x_5 = 9
3x_5 = 9



In [244]:
#some other useful matrix decomposition techniques
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Q, R = scipy.linalg.qr(M)
print("M:")
print(M)
print("QR decomposition of matrix M (Q first, R second):")
print(Q)
print(R)

M:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
QR decomposition of matrix M (Q first, R second):
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]
